//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPPOLSyncProgram.CustomDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRegistration
    {
        public string UEN { get; set; }
        public string CompanyName { get; set; }
        public string GSTRegistrationNumber { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string PostalCode { get; set; }
        public string AuthorizedPersonnelName { get; set; }
        public string AuthorizedPersonnelEmail { get; set; }
        public string AuthorizedPersonnelContactNumber { get; set; }
        public bool SubmitToStarHub { get; set; }
        public bool IsApproved { get; set; }
        public string PEPPOLID { get; set; }
    }
}
