//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPPOLSyncProgram.CustomDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PEPPOLEntities : DbContext
    {
        public PEPPOLEntities()
            : base("name=PEPPOLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Errors> Errors { get; set; }
        public virtual DbSet<SyncErrLog> SyncErrLog { get; set; }
        public virtual DbSet<CustomerRegistration> CustomerRegistration { get; set; }
    }
}
