//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPPOLSyncProgram.CustomDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int Idkey { get; set; }
        public string traceId { get; set; }
        public string timestamp { get; set; }
        public string eventType { get; set; }
        public string outcome { get; set; }
        public string primarysubjectid { get; set; }
        public string secondarysubjectid { get; set; }
        public string message { get; set; }
        public Nullable<bool> SubmitToSAP { get; set; }
    }
}
