//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPPOLSyncProgram.CustomDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncErrLog
    {
        public int IdKey { get; set; }
        public string errMsg { get; set; }
        public string InnerException { get; set; }
        public string FileName { get; set; }
        public string LineNumber { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
